export const ERROR_ON_WRITE_ELECTRONIC_URN = "ERROR_ON_WRITE_ELECTRONIC_URN";
export const ERROR_INPUT_BU_CANNOT_BY_EMPTY = "ERROR_INPUT_BU_CANNOT_BY_EMPTY";
export const SUCCESSFULLY_ELECTION_ADDED = "SUCCESSFULLY_ELECTION_ADDED"
export const SUCCESSFULLY_ELECTRONIC_URN_ADDED = "SUCCESSFULLY_ELECTRONIC_URN_ADDED"
export const ERROR_CANNOT_ADD_ELECTRONIC_URN_WITHOUT_HASH = "ERROR_CANNOT_ADD_ELECTRONIC_URN_WITHOUT_HASH"
export const ERROR_ELECTRONIC_URN_ALREADY_EXIST = "ERROR_ELECTRONIC_URN_ALREADY_EXIST"
export const ERROR_QR_CODE_RECEIVE_INVALID = "ERROR_QR_CODE_RECEIVE_INVALID"
export const ERROR_PERMISSION_DENIED = "ERROR_PERMISSION_DENIED"


export const JobNames = {
  "1": "Presidente",
  "3": "Governador",
  "5": "Senador",
  "6": "Deputado Federal",
  "7": "Deputado Estadual",
  "8": "Deputado Distrital",
  "9": "Conselheiro Distrital",
  "11": "Prefeito",
  "13": "Vereador",
}
